### ISSUE TITLE
Looking to just install core to build prism model

### ISSUE THREAD

**Issue by oyendrila-dobe** [moves-rwth/stormpy#44]
I'm utilizing stormpy's parse_prism_program() and build_model() functionalities. I see that it mostly just requires the core package of stormpy. Is there a way to just generate the core package? And once the .so is generated, would it still work if I intend to move it to a different directory in my machine?

**Comment by volkm** [comment]
You can disable some of the functionality for compilation with `--disable-dft --disable-gspn --disable-pars --disable-pomdp`. See the [documentation](https://moves-rwth.github.io/stormpy/installation.html#optional-build-arguments) for some pointers.

You can try out what happens if you move the .so file, but my guess it that it might not work so easily. At least you probably would need to adapt some paths.
